### PR TITLE
Update Media "downloadFile" example on README

### PR DESCRIPTION
**Pull request by ikeorizu**

### CODE REVIEW

**Comment by FabienLavocat** [comment]
Thank you @ikeorizu for this pull request, this is a good catch! Could you please sign the [Contribution Agreement](https://contribute.dolby.io/) and I will merge your pull request.

**Review by FabienLavocat — APPROVED** [review]

**Comment by ikeorizu** [comment]
Always welcome @FabienLavocat, Signed the agreement as well.

**Comment by FabienLavocat** [comment]
@ikeorizu could you please give it another try with the signature, it looks like the first time did not work.

**Comment by ikeorizu** [comment]
Weird, I have signed both individual and for our company @FabienLavocat. Am I missing another step ?

**Comment by FabienLavocat** [comment]
Apologies @ikeorizu we have received the signature, looks like a minor issue in the bot, I'll merge this PR. Thanks again for the contribution!

**Pull request merged**
